// frontend-react/src/Views/PreviewPage.js
import React from "react";
import BigBlock from "../Components/PreviewPage/BigBlock";
import CardBlock from "../Components/PreviewPage/CardBlock";
import sqrt from '../Assets/PreviewPageSqrt.png';
import circleOk from '../Assets/CircleOk.png';
import school from '../Assets/School.png';

export default class TestPage extends React.Component {
  constructor(props) {
    super(props);
    document.title = "MathProjMVP"
  }

  render() {
    let firstBlockHeading = "Стань другом с Математикой";
    let secondBlockHeading = "Для преподaвателей";
    let BlockText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n" +
      "Nullam efficitur diam et urna venenatis, ac rutrum justo egestas.";

    let cardBlockHeading1 = "Закрой свои слабые места";
    let cardBlockText1 = "Lorem ipsum dolor sit amet. consectetur adipiscing elit.\n" +
      "Nullam efficitur diam et urna venenatis. ac rutrum justo egestas."

    return (
      <div className="fade-in-top">
        <BigBlock
          className="prev-page-big-block"
          heading={firstBlockHeading}
          text={BlockText}
          image={sqrt}
          imgAliginRight={true}
        />
        <div className="prev-page-card">
          <CardBlock
            className="prev-page-card-block"
            heading={cardBlockHeading1}
            text={cardBlockText1}
            image={circleOk}
          />
          <CardBlock
            className="prev-page-card-block"
            heading={cardBlockHeading1}
            text={cardBlockText1}
            image={circleOk}
          />
          <CardBlock
            className="prev-page-card-block"
            heading={cardBlockHeading1}
            text={cardBlockText1}
            image={circleOk}
          />
        </div>
        <BigBlock
          className="prev-page-big-block"
          heading={secondBlockHeading}
          text={BlockText}
          image={school}
          imgAliginRight={false}
        />
      </div>
    );
  }
}

// frontend/src/views/PreviewPage.vue
<template>
  <div class="prv-page fade-in-top">
    <BigBlock
      :heading=firstBlockHeading
      :text=BlockText
      :image=sqrt
      :img_align_right=true
    ></BigBlock>
    <div class="prev-page-card">
      <CardBlock
        :heading=cardBlockHeading1
        :text=cardBlockText1
        :image=circleOk
      ></CardBlock>
      <CardBlock
        :heading=cardBlockHeading1
        :text=cardBlockText1
        :image=circleOk
      ></CardBlock>
      <CardBlock
        :heading=cardBlockHeading1
        :text=cardBlockText1
        :image=circleOk
      ></CardBlock>
    </div>
    <BigBlock
      :heading=secondBlockHeading
      :text=BlockText
      :image=school
      :img_align_right=false
    ></BigBlock>
  </div>
</template>

<script>
  import BigBlock from "../components/PreviewPage/BigBlock";
  import CardBlock from "../components/PreviewPage/CardBlock";
  import sqrt from '../assets/PreviewPageSqrt.png';
  import circleOk from '../assets/CircleOk.png';
  import school from '../assets/School.png';

  export default {
    name: "PreviewPage",
    components: {CardBlock, BigBlock},
    props: {
    },
    data() {
      return {
        firstBlockHeading: "Стань другом с Математикой",
        secondBlockHeading: "Для преподaвателей",
        BlockText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit." +
          "Nullam efficitur diam et urna venenatis, ac rutrum justo egestas.",
        cardBlockHeading1: "Закрой свои слабые места",
        cardBlockText1: "Lorem ipsum dolor sit amet. consectetur adipiscing elit." +
          "Nullam efficitur diam et urna venenatis. ac rutrum justo egestas.",
        sqrt: sqrt,
        circleOk: circleOk,
        school: school
      }
    }
  }
</script>

<style lang="scss">
  .prv-page {
    margin-top: 20px;
  }
  .prev-page-card {
    display: flex;
    flex-direction: row;
    justify-content: space-evenly;
    align-items: center;
    margin-top: 100px;
    margin-bottom: 100px;
  }
</style>
